# Generated by Django 2.2.7 on 2019-12-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191218_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='result',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
